## server port config
server:
  port: 8001
  servlet:
    session:
      timeout: 1800
  error:
    path: /error



## driver config
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crmdb
    username: ohgiraffers
    password: ohgiraffers
  servlet:
    multipart:
      location: D:\lecture\GymGa-Project

## mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml